id: ADD14D661
title: S훮dhana of M훮r카c카
type: translation
pechas:
- I4859B9B5
- I826E6BBC
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 13:11:45.375736
  last_modified_at: 2023-01-04 13:11:45.375746
  collections:
  - Mipham Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  I4859B9B5/4BD8: EC44
  I826E6BBC/35B7: EC44
